site_name: Engine Pi
site_url: https://engine-pi.github.io/engine-pi/
theme:
  name: material
  logo: assets/logo.svg
  font:
    text: Cantarell
    code: Ubuntu Mono
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    # index.md in Ordner werden nicht doppelt angezeigt
    - navigation.indexes

repo_name: Engine Pi
repo_url: https://github.com/engine-pi/engine-pi

plugins:
  # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
  - macros
  # https://github.com/tuunit/mkdocs-drawio
  - drawio
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/
  # /// caption Caption ///
  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css

watch:
  - docs

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
nav:
  - Ãœber die Engine Pi: index.md
  - Referenz:
      - reference/koordinatensystem.md
      - reference/figur.md
      - reference/kamera.md
      - reference/ressourcen.md
      - reference/bilderschriftart.md
      - reference/zeitsteuerung.md
      - reference/ereignissteuerung.md
      - reference/physics.md
  - Tutorials:
      - tutorials/index.md
      - tutorials/01_hello-world.md
      - tutorials/02_user-input.md
      - tutorials/03_game-loop.md
      - tutorials/04_scenes.md
      - tutorials/05_physics.md
      - tutorials/06_stateful-animation.md
      - tutorials/07_collision.md
  - API (javadocs): https://javadoc.io/doc/de.pirckheimer-gymnasium/engine-pi/latest/index.html
  - java.md
  - download.md

extra:
    version: 0.41.0
