site_name: Engine Pi
site_url: https://engine-pi.github.io/docs/
theme:
  name: material
  font:
      text: Cantarell
      code: Ubuntu Mono

repo_name: Engine Pi
repo_url: https://github.com/engine-pi/engine-pi

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - pymdownx.magiclink
# https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption


extra_css:
  - stylesheets/extra.css

watch:
  - docs
