site_name: Engine Pi
site_url: https://engine-pi.github.io/engine-pi/

repo_name: Engine Pi
repo_url: https://github.com/engine-pi/engine-pi
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _assets/logo.svg
  font:
    text: Cantarell
    code: Ubuntu Mono
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    # index.md in Ordner werden nicht doppelt angezeigt
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation
    - navigation.footer
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-copy-button
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#code-selection-button
    - content.code.select
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    # - content.action.view

plugins:
  # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
  - macros:
      # https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
      module_name: docs/macros

  # https://github.com/tuunit/mkdocs-drawio
  - drawio
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/manual/footnotes/
  - footnotes
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/manual/images/
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/grids/
  - md_in_html
  # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/
  # /// caption Caption ///
  - pymdownx.blocks.caption

  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - _assets/extra.css

# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#arithmatex-mkdocsyml
extra_javascript:
  - _assets/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

watch:
  - docs

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
nav:
  - Handbuch:
      - Hauptklassen:
          - manual/main-classes/index.md
          - Controller (Steuerung):
              - manual/main-classes/controller/index.md
              - manual/main-classes/controller/coordinate-system.md
              - manual/main-classes/controller/instant-mode.md
              - manual/main-classes/controller/game-loop.md
              - manual/main-classes/controller/dialog.md
          - manual/main-classes/scene.md
          - manual/main-classes/camera.md
          - manual/main-classes/layer.md
          - 'Actor (Figur)':
              - manual/main-classes/actor/index.md
              - manual/main-classes/actor/hello-world.md
              - manual/main-classes/actor/turtle.md
              - manual/main-classes/actor/image-font.md
              - manual/main-classes/actor/stateful-animation.md

      - events (Ereignissteuerung):
          - manual/events/index.md
          - manual/events/key-event.md
          - manual/events/key-stroke.md
          - manual/events/mouse-click.md
          - manual/events/collision.md
          - manual/events/repeat.md
          - manual/events/shortcuts.md

      - physics (Physiksimulation):
          - manual/physics/index.md
          - manual/physics/body-type.md
          - manual/physics/gravity.md
          - manual/physics/density.md
          - manual/physics/restitution.md
          - manual/physics/impulse.md
          - manual/physics/joints.md

      - Ressourcenverwaltung:
          - manual/resources/index.md
          - manual/resources/colors.md
          - manual/resources/fonts.md
          - manual/resources/images.md
          - manual/resources/sounds.md

      - Java:
          - manual/java/index.md
          - manual/java/packages.md

      - Entwicklung:
          - manual/dev/index.md
          - manual/dev/monorepo.md
          - manual/dev/design.md
          - manual/dev/coding-style.md
          - manual/dev/javadoc.md
          - manual/dev/mkdocs.md
          - manual/dev/setter-getter.md
          - manual/dev/versions.md

  - API (javadocs): https://engine-pi.github.io/javadocs/pi/package-summary.html

  - download.md

extra:
  version: 0.41.0
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice
  generator: false

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/engine-pi/engine-pi
    - icon:  simple/forgejo
      link: https://inf.pirckheimer-gymnasium.de/engine-pi/engine-pi
    - icon: fontawesome/brands/java
      link: https://engine-pi.github.io/javadocs/pi/package-summary.html
    - icon: fontawesome/solid/paper-plane
      link: mailto:josef.friedrich@pirckheimer-gymnasium.de

# https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#copyright-notice
copyright: Copyright &copy; 2024 - 2026 Josef Friedrich
