site_name: Engine Pi
site_url: https://engine-pi.github.io/engine-pi/

repo_name: Engine Pi
repo_url: https://github.com/engine-pi/engine-pi
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
edit_uri: edit/main/docs/

theme:
  name: material
  logo: _assets/logo.svg
  font:
    text: Cantarell
    code: Ubuntu Mono
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
    # index.md in Ordner werden nicht doppelt angezeigt
    - navigation.indexes
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#navigation
    - navigation.footer
    # https://squidfunk.github.io/mkdocs-material/manual/code-blocks/#code-copy-button
    - content.code.copy
    # https://squidfunk.github.io/mkdocs-material/manual/code-blocks/#code-selection-button
    - content.code.select
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    - content.action.edit
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    # - content.action.view

plugins:
  # https://mkdocs-macros-plugin.readthedocs.io/en/latest/
  - macros:
      # https://mkdocs-macros-plugin.readthedocs.io/en/latest/macros/
      module_name: docs/macros

  # https://github.com/tuunit/mkdocs-drawio
  - drawio
markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/manual/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#inlinehilite
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/manual/footnotes/
  - footnotes
  - pymdownx.magiclink
  # https://squidfunk.github.io/mkdocs-material/manual/images/
  - attr_list
  - md_in_html
  # https://facelessuser.github.io/pymdown-extensions/extensions/blocks/plugins/caption/
  # /// caption Caption ///
  - pymdownx.blocks.caption

  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details

extra_css:
  - _assets/extra.css

watch:
  - docs

# https://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages
nav:
  - Ãœber die Engine Pi: index.md
  - Handbuch:
      - Hauptklassen:
          - manual/main-classes/index.md
          - 'Actor (Figur)':
              - manual/main-classes/actor/index.md
              - manual/main-classes/actor/turtle.md
              - manual/main-classes/actor/stateful-animation.md
          - manual/main-classes/scene.md
          - manual/main-classes/camera.md
          - manual/main-classes/layer.md
          - Game (Spiel):
              - manual/main-classes/game/index.md
              - manual/main-classes/game/dialog.md

      - events (Ereignissteuerung):
          - manual/events/index.md
          - manual/events/key-stroke-listener.md
          - manual/events/mouse-click-listener.md
          - manual/events/collision-listener.md

      - Ressourcenverwaltung:
          - manual/resources/index.md
          - manual/resources/colors.md
          - manual/resources/fonts.md
          - manual/resources/images.md
          - manual/resources/sounds.md

  #     - manual/koordinatensystem.md
  #     - manual/kamera.md
  #     - manual/ressourcen.md
  #     - manual/bilderschriftart.md
  #     - manual/zeitsteuerung.md
  #     - manual/ereignissteuerung.md
  #     - manual/physics.md
  #     - manual/programmierstil.md
  # - Tutorials:
  #     - tutorials/index.md
  #     - tutorials/01_hello-world.md
  #     - tutorials/02_user-input.md
  #     - tutorials/03_game-loop.md
  #     - tutorials/04_scenes.md
  #     - tutorials/05_physics.md
  #     - tutorials/06_stateful-animation.md
  #     - tutorials/07_collision.md
  - API (javadocs): https://engine-pi.github.io/javadocs/pi/package-summary.html
  - download.md

extra:
  version: 0.41.0
